[package]
name = "static_hashmap"
version = "0.1.0"
authors = ["Yukiteru Lee <wfly1998@sina.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.1.0"

